--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "GOSALES_IDA3"."CUST" (
		"CUST_CODE" INTEGER NOT NULL, 
		"CUST_FRST_NAME" VARCHAR(128), 
		"CUST_LAST_NAME" VARCHAR(128), 
		"CUST_ADDR1" VARCHAR(128), 
		"CUST_CITY" VARCHAR(128), 
		"CUST_POST_ZONE" VARCHAR(100), 
		"CUST_CTRY_CODE" VARCHAR(128), 
		"CUST_PHN_NBR" VARCHAR(120), 
		"CUST_INFO" CLOB(32768), 
		"CUST_EMAIL" CHAR(5), 
		"CUST_GNDR_CODE" DECIMAL(3 , 0), 
		"CUST_PROV_STATE" VARCHAR(128)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "GOSALES_IDA3"."CUST_CRDTCRD" (
		"CRDTCRD_ID" INTEGER NOT NULL, 
		"CUST_CODE" INTEGER NOT NULL, 
		"CRDTCRD_PRIMARY_ACCT_NBR" INTEGER, 
		"CRDTCRD_SERV_CODE" INTEGER, 
		"CRDTCRD_EXP_DATE" DATE
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "GOSALES_IDA3"."CUST_INV" (
		"ORD_NBR" INTEGER NOT NULL, 
		"ORD_INV" XML, 
		"CUST_CODE" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "GOSALES_IDA3"."CUST_ORD" (
		"ORD_NBR" INTEGER NOT NULL, 
		"ORD_DATE" DATE, 
		"ORD_NBR_OF_ITEMS" INTEGER, 
		"ORD_NBR_OF_PRODS" INTEGER, 
		"ORD_STOT_COST" DECIMAL(30 , 2), 
		"ORD_SHIP_COST" DECIMAL(30 , 2), 
		"ORD_TAX_COST" DECIMAL(30 , 2), 
		"ORD_TOT_COST" DECIMAL(30 , 2), 
		"ORD_PYMT_METH" VARCHAR(128), 
		"ORD_STAT" VARCHAR(128), 
		"ORD_METH_CODE" INTEGER NOT NULL, 
		"CUST_CRDTCRD_ID" INTEGER NOT NULL, 
		"CUST_CODE" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "GOSALES_IDA3"."PTNR_ACTY" (
		"PTNR_CODE" INTEGER NOT NULL, 
		"ORD_NBR" INTEGER NOT NULL, 
		"ORD_STOT_COST" DECIMAL(30 , 2), 
		"ORD_SHIP_COST" DECIMAL(30 , 2), 
		"ORD_TAX_COST" DECIMAL(30 , 2), 
		"ORD_TOT_COST" DECIMAL(30 , 2), 
		"ORD_STAT" VARCHAR(128), 
		"PTNR_INV" XML, 
		"CUST_CODE" INTEGER NOT NULL, 
		"PTNR_CUST_CODE" VARCHAR(10)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "GOSALES_IDA3"."PTNR_CNTCT" (
		"PTNR_CODE" INTEGER NOT NULL, 
		"PTNR_CO_NAME" VARCHAR(128), 
		"PTNR_FRST_NAME" VARCHAR(128), 
		"PTNR_LAST_NAME" VARCHAR(128), 
		"PTNR_CITY" VARCHAR(128), 
		"PTNR_ADDR1" VARCHAR(128), 
		"PTNR_PROV_STATE" VARCHAR(128), 
		"PTNR_POST_ZONE" VARCHAR(100), 
		"PTNR_CTRY_CODE" VARCHAR(128), 
		"PTNR_INFO" XML, 
		"ORD_NBR" INTEGER NOT NULL, 
		"PTNR_SALES" DECIMAL(30 , 2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

