--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "GOSALES_IDA_2"."CUSTOMER" (
		"CUSTOMER_CODE" INTEGER NOT NULL, 
		"CUSTOMER_FIRST_NAME" VARCHAR(128), 
		"CUSTOMER_LAST_NAME" VARCHAR(128), 
		"CUSTOMER_ADDRESS1" VARCHAR(128), 
		"CUSTOMER_CITY" VARCHAR(128), 
		"CUSTOMER_POSTAL_ZONE" VARCHAR(100), 
		"CUSTOMER_COUNTRY_CODE" VARCHAR(128), 
		"CUSTOMER_PHONE_NUMBER" VARCHAR(120), 
		"CUSTOMER_INFO" CLOB(32768), 
		"CUSTOMER_EMAIL" VARCHAR(128), 
		"CUSTOMER_GENDER_CODE" DECIMAL(3 , 0), 
		"CUSTOMER_PROVINCE_STATE" VARCHAR(128)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "GOSALES_IDA_2"."CUSTOMER_CREDITCARD" (
		"CREDITCARD_ID" INTEGER NOT NULL, 
		"CUSTOMER_CODE" INTEGER NOT NULL, 
		"CREDITCARD_PRIMARY_ACCOUNT_NUMBER" INTEGER, 
		"CREDITCARD_SERVICE_CODE" INTEGER, 
		"CREDITCARD_EXP_DATE" DATE
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "GOSALES_IDA_2"."CUSTOMER_INVOICE" (
		"ORDER_NUMBER" INTEGER NOT NULL, 
		"ORDER_INVOICE" XML, 
		"CUSTOMER_CODE" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "GOSALES_IDA_2"."CUSTOMER_ORDER" (
		"ORDER_NUMBER" INTEGER NOT NULL, 
		"ORDER_DATE" DATE, 
		"ORDER_NUMBER_OF_ITEMS" INTEGER, 
		"ORDER_NUMBER_OF_PRODUCTS" INTEGER, 
		"ORDER_SUBTOTAL_COST" DECIMAL(30 , 2), 
		"ORDER_SHIPPING_COST" DECIMAL(30 , 2), 
		"ORDER_TAX_COST" DECIMAL(30 , 2), 
		"ORDER_TOTAL_COST" DECIMAL(30 , 2), 
		"ORDER_PAYMENT_METHOD" VARCHAR(128), 
		"ORDER_STATUS" VARCHAR(128), 
		"ORDER_METHOD_CODE" INTEGER NOT NULL, 
		"CUSTOMER_CREDITCARD_ID" INTEGER NOT NULL, 
		"CUSTOMER_CODE" INTEGER NOT NULL
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "GOSALES_IDA_2"."PARTNER_ACTIVITY" (
		"PARTNER_CODE" INTEGER NOT NULL, 
		"ORDER_NUMBER" INTEGER NOT NULL, 
		"ORDER_SUBTOTAL_COST" DECIMAL(30 , 2), 
		"ORDER_SHIPPING_COST" DECIMAL(30 , 2), 
		"ORDER_TAX_COST" DECIMAL(30 , 2), 
		"ORDER_TOTAL_COST" DECIMAL(30 , 2), 
		"ORDER_STATUS" VARCHAR(128), 
		"PARTNER_INVOICE" XML, 
		"CUSTOMER_CODE" INTEGER NOT NULL, 
		"PARTNER_CUSTOMER_CODE" VARCHAR(10)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "GOSALES_IDA_2"."PARTNER_CONTACT" (
		"PARTNER_CODE" INTEGER NOT NULL, 
		"PARTNER_COMPANY_NAME" VARCHAR(128), 
		"PARTNER_FIRST_NAME" VARCHAR(128), 
		"PARTNER_LAST_NAME" VARCHAR(128), 
		"PARTNER_ADDRESS1" VARCHAR(128), 
		"PARTNER_PROVINCE_STATE" VARCHAR(128), 
		"PARTNER_POSTAL_ZONE" VARCHAR(100), 
		"PARTNER_COUNTRY_CODE" VARCHAR(128), 
		"PARTNER_CITY" VARCHAR(128), 
		"PARTNER_INFO" XML, 
		"ORDER_NUMBER" INTEGER NOT NULL, 
		"PARTNER_SALES" DECIMAL(30 , 2)
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

